<?php

/**
 * VerbSeeder
 * Created by: Marc-Eli Faldas
 * Last Modified: 5/08/2018
 */

use Illuminate\Database\Seeder;
use App\Verb;

class VerbsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * @return void
     */
    public function run()
    {
        $verbs = [
            ['absent', 'liban', 'lumiban', 'lumiliban', 'liliban', '休む (やすみ)'],
            ['abuse', 'abuso', 'umabuso', 'umaabuso', 'aabuso', '乱用する（らんようする)'],
            ['accept', 'tanggap', 'tumanggap', 'tumatanggap', 'tatanggap', '受け入れる（うけいれる)'],
            ['accuse', 'akusa', 'nag-akusa', 'nang-aakusa', 'mang-aakusa', '争い訴える（あらそいうったえる)'],
            ['acquire', 'kuha', 'kumuha', 'kumukuha', 'kukuha', 'もらう'],
            ['add', 'dagdag', 'nagdagdag', 'nagdaragdag', 'magdaragdag', '加える（くわえる)'],
            ['advance (forward)', 'sulong', 'sumulong', 'sumusulong', 'susulong', '進む (すすむ)'],
            ['angry (to be angry)', 'galit', 'nagalit', 'nagagalit', 'magagalit', '起こる (おこる)'],
            ['angry (to make someone)', 'galit', 'nanggalit', 'nanggagalit', 'manggalit', 'N/A'],
            ['angry (scold someone)', 'galit', 'pinagalitin', 'pinapapagalitan', 'papagalitan', 'しかる'],
            ['annoy (someone)', 'inis', 'nang-inis', 'nang-iinis', 'mang-iinis', '迷惑をかける (めいわくをかける)'],
            ['approach', 'lapit', 'lumapit', 'lumalapit', 'lalapit', '近づく (ちかづく)'],
            ['arrive', 'dating', 'dumating', 'dumarating', 'darating', 'くる'],
            ['ask for (something)', 'hingi', 'humingi', 'humihingi', 'hihingi', '頼む (たのむ)'],
            ['ask about', 'tanong', 'nagtanong', 'nagtatanong', 'magtatanong', 'きく'],
            ['assume', 'akala', 'nag-akala', 'nag-aakala', 'mag-aakala', 'N/A'],
            ['attack', 'lusob', 'lumusob', 'lumulusob', 'lulusob', '襲う (おそう)'],
            ['attend', 'dalo', 'dumalo', 'dumadalo', 'dadalo', '出る (でる)'],
            ['attention(give)', 'pansin', 'napansin', 'napapansin', 'mapapansin', '注目(ちゅうもくする)'],
            ['attract', 'akit', 'naakit', 'naaakit', 'maaakit', 'ひく'],
            ['avoid', 'layó', 'lumayó', 'lumalayó', 'lalayó', 'さく'],
            ['bad (to become)', 'samá', 'sumamá', 'sumasamá', 'sasamá', 'N/A'],
            ['ban', 'bawal', 'nagbawal', 'nagbabawal', 'magbabawal', '禁じる (きんじる)'],
            ['begin', 'umpisa', 'nag-umpisa', 'nag-uumpisa', 'mag-uumpisa', '始める(はじめる)/始る(はじまる)'],
            ['believe', 'niwala', 'naniwala', 'naniniwala', 'maniniwala', '信じる (しんじる)'],
            ['big (to become)', 'laki', 'lumaki', 'lumalaki', 'lalaki', '太る (ふとる)'],
            ['big (to make it)', 'laki', 'nilakihan', 'nilalakihan', 'lalakihan', 'N/A'],
            ['birth (to give birth)', 'anak', 'nanganak', 'nanganganak', 'manganganak', 'うむ'],
            ['bite', 'kagat', 'kumagat', 'kumakagat', 'kakagat', '噛む (かむ)'],
            ['boil', 'laga', 'naglaga', 'naglalaga', 'maglalaga', '沸く (わく)'],
            ['borrow', 'hiram', 'humiram', 'humihiram', 'hihiram', '借りる (かりる)'],
            ['borrow (money)', 'utang', 'umutang', 'umuutang', 'uutang', 'N/A'],
            ['break', 'sirá', 'sumirá', 'sumisirá', 'sisirá', '切れる'],
            ['break (glassware)', 'basag', 'nagbasag', 'nagbabasag', 'magbabasag', 'N/A'],
            ['break (tear)', 'punit', 'pumunit', 'pumupunit', 'pupunit', 'やぶる'],
            ['break (long objects)', 'balí', 'bumalí', 'bumabalí', 'babalí', 'N/A'],
            ['break (out of order)', 'sirá', 'nagsirá', 'nagsisirá', 'magsisirá', 'N/A'],
            ['break (irreparable)', 'wasak', 'nagwasak', 'nagwawasak', 'magwawasak', 'N/A'],
            ['breathe', 'hinge', 'humina', 'humihinga', 'hihinga', '息をする, (いきをする)'],
            ['bring', 'hatid', 'naghatid', 'naghahatid', 'maghahatid', 'N/A'],
            ['bring along', 'sáma', 'nagsáma', 'nagsasáma', 'magsasáma', 'N/A'],
            ['bring home', 'uwí', 'nag - uwí', 'nag-uuwí', 'mag - uuwí', 'N/A'],
            ['bring out', 'labas', 'naglabas', 'naglalabas', 'maglalabas', 'N/A'],
            ['bring to life', 'buhay', 'bumuhay', 'bumubuhay', 'bubuhay', 'N/A'],
            ['bring up', 'akyat', 'nag-akyat', 'nag-aakyat', 'mag-aakyat', 'N/A'],
            ['brush (teeth)', 'sipilyo (brush)', 'nagsipilyo (nag-brush)', 'nagsisipilyo (nagba-brush)', 'magsisipilyo (magba-brush)', '歯を磨く（はをみがく）'],
            ['brush (hair)', 'suklay (brush)', 'nagsuklay (nag-brush)', 'nagsusuklay (nagba-brush)', 'magsusuklay (magba-brush)', '撫でる（なでる）'],
            ['build', 'tayó', 'nagtayó', 'nagtatayó', 'magtatayó', '作る'],
            ['burn', 'sunog', 'nagsunog', 'nagsusunog', 'magsusunog', '燃える'],
            ['burp', 'dighay', 'dumighay', 'dumidighay', 'didighay', 'N/A'],
            ['buy', 'bili', 'bumili', 'bumibili', 'bibili', '買う（かう）'],
            ['call', 'tawag', 'tumawag', 'tumatawag', 'tatawag', '呼び出す（よびだす）'],
            ['call up (phone)', 'tawag', 'tumawag', 'tumatawag', 'tatawag', '電話をかける（でんわをかける）'],
            ['carry', 'dala', 'nagdala', 'nagdadala', 'magdadala', '運ぶ（はこぶ）'],
            ['carry (on the head)', 'sunong', 'nagsunong', 'nagsusunong', 'magsusunong', 'N/A'],
            ['carry (on the back)', 'pasan', 'nagpasan', 'nagpapasan', 'magpapasan', 'N/A'],
            ['carry (with arm)', 'bitbit', 'nagbitbit', 'nagbibitbit', 'magbibitbit', 'N/A'],
            ['catch (something)', 'saló', 'sumaló', 'sumasaló', 'sasaló', 'N/A'],
            ['catch (someone)', 'huli', 'humuli', 'humuhuli', 'huhuli', 'N/A'],
            ['catch up (someone)', 'abot', 'nag-abot', 'nag-aabot', 'mag-aabot', 'N/A'],
            ['change', 'palit', 'nagpalit', 'nagpapalit', 'magpapalit', '変わる（かわる）'],
            ['change(clothes)', 'bihis', 'nagbihis', 'nagbibihis', 'magbibihis', '着替える（きがえる）'],
            ['cheat', 'daya', 'nandaya', 'nandadaya', 'mandadaya', 'だます（だます）'],
            ['choose', 'pili', 'pumili', 'pumipili', 'pipili', '選ぶ（えらぶ）'],
            ['clap', 'palakpak', 'pumalakpak', 'pumapalakpak', 'papalakpak', '手を叩く（てをたたく）'],
            ['clean', 'linis', 'naglinis', 'naglilinis', 'maglilinis', '掃除する（そうじする）'],
            ['damage', 'sirá', 'sumirá', 'sumisirá', 'sisirá', '損害する（そんがいする）'],
            ['dance', 'sayaw', 'sumayaw', 'sumasayaw', 'sasayaw', '踊る（おどる）'],
            ['deceive', 'linlang', 'nanglinlang', 'nanlilinlang', 'manlilinlang', '欺く(あざむく）'],
            ['deliver', 'dalá', 'nagdalá', 'nagdadalá', 'magdadalá', '届ける（とどける）'],
            ['depart', 'alís', 'umalís', 'umaalís', 'aalís', '出る（でる）'],
            ['destroy', 'sirá', 'nanirá', 'naninirá', 'maninirá', '損害する（そんがいする）'],
            ['destroy (character)', 'linis', 'naglinis', 'naglilinis', 'maglilinis', 'N/A'],
            ['develop', 'unlad', 'umunlad', 'umuunlad', 'uunlad', 'N/A'],
            ['die', 'patay', 'namatay', 'namamatay', 'mamamatay', 'N/A'],
            ['divide', 'hatí', 'naghatí', 'naghahatí', 'maghahatí', '死む（しむ）'],
            ['dizzy', 'hílo', 'nahílo', 'nahihílo', 'mahihílo', '目が回る（めがまわる）'],
            ['do', 'gáwa', 'gumáwa', 'ginagawa', 'gagawa', 'する'],
            ['draw(picture)', 'guhit', 'nagguhit', 'nagguguhit', 'magguguhit', '書く（かく）'],
            ['dress(put on)', 'bihis', 'nagbihis', 'nagbibihis', 'magbibihis', '着る（きる）/　はく'],
            ['eat', 'kain', 'kumain', 'kumakain', 'kakain', '食べる（たべる）'],
            ['elevate', 'táas', 'nagtáas', 'nagtatáas', 'magtatáas', 'N/A'],
            ['elope', 'tanan', 'nagtanan', 'nagtatanan', 'magtatanan', '駆け落ちする（かけおちする）'],
            ['embrace', 'yakap', 'yumakap', 'yumayakap', 'yayakap', '抱く（いだく）'],
            ['enjoy', 'sayá', 'nagsayá(nag-enjoy)', 'nagsasayá(nage-enjoy)', 'magsasayá(mage-enjoy)', 'N/A'],
            ['enter (a place)', 'pasok', 'pumasok', 'pumapasok', 'papasok', '入る（はいる）'],
            ['enter into', 'suót', 'sumuót', 'sumusuót', 'susuót', '入る（はいる）'],
            ['entertain', 'libang', 'naglibang', 'naglilibang', 'manlilibang', 'N/A'],
            ['erase', 'burá', 'nagburá', 'nagbuburá', 'magbuburá', '消す（けす）'],
            ['examine (analyze)', 'surí', 'nagsurí', 'nagsusurí', 'magsusurí', '調べると（しらべる）'],
            ['examine (medical)', 'tingín', 'nagpatingín', 'nagpapatingín', 'magpapatingín', 'N/A'],
            ['examine (test)', 'sulit', 'nagsulit(nag-exam)', 'nagsusulit(nage-exam)', 'magsusulit(mage-exam)', 'N/A'],
            ['expect', 'ása', 'umása', 'umaása', 'aása', 'N/A'],
            ['exit', 'lábas', 'lumábas', 'lumalábas', 'lalábas', '出る（でる）'],
            ['face toward', 'hárap', 'humárap', 'humahárap', 'hahárap', 'N/A'],
            ['fall', 'hulog', 'nahulog', 'nahuhulog', 'mahuhulog', '倒れる（たおれる）'],
            ['farm', 'saká', 'nagsaká', 'nagsasaká', 'magsasaká', '畑を作る（はたけをつくる）'],
            ['fart', 'útot', 'umútot', 'umuútot', 'uútot', 'へをひる'],
            ['feed', 'kain', 'nagpakain', 'nagpapakain', 'magpapakain', 'N/A'],
            ['feel (bad)', 'damdám', 'nagdamdám', 'nagdaramdám', 'magdaramdám', 'N/A'],
            ['feel (something)', 'dama', 'dumama', 'dumama', 'dadama', 'N/A'],
            ['feel (better)', 'gáling', 'gumáling', 'gumagáling', 'gagáling', 'N/A'],
            ['fight', 'laban', 'lumaban', 'lumalaban', 'lalaban', '殴る（なぐる）'],
            ['fill up (container)', 'punó', 'nagpunó', 'nagpupunó', 'magpupunó', 'N/A'],
            ['find', 'hanap', 'humanap', 'humahanap', 'hahanap', 'N/A'],
            ['fish', 'isdá', 'nangisdá', 'nangingisdá', 'mangisdá', 'つる'],
            ['fly', 'lípad', 'lumípad', 'lumilípad', 'lilípad', '飛ぶ（とぶ）'],
            ['follow after', 'súnod', 'sumúnod', 'sumusúnod', 'susúnod', 'N/A'],
            ['forget (someone)', 'limot', 'lumimot', 'lumilimot', 'lilimot', '忘れる（わすれる）'],
            ['gamble', 'sugal', 'nagsugal', 'nagsusugal', 'magsusugal', 'かける'],
            ['get', 'kuhá', 'kumuhá', 'kumukuhá', 'kukuhá', 'くれる'],
            ['gift (to give)', 'regalo', 'nagregalo', 'nagreregalo', 'magreregalo', 'N/A'],
            ['give', 'bigay', 'nagbigay', 'nagbibigay', 'magbibigay', 'N/A'],
            ['give up (surrender)', 'sukó', 'sumukó', 'sumusukó', 'susukó', 'あきらめる'],
            ['go (to a place)', 'puntá', 'pumuntá', 'pumupuntá', 'pupuntáhan', '行く（いく）'],
            ['go away', 'layas', 'lumayas', 'lumalayas', 'lalayas', 'N/A'],
            ['go down', 'babá', 'bumabá', 'bumababá', 'bababá', 'N/A'],
            ['go on', 'tuloy', 'tumuloy', 'tumutuloy', 'tutuloy', 'N/A'],
            ['go out', 'labas', 'lumabas', 'lumalabas', 'lalabas', 'N/A'],
            ['go up', 'akyat', 'umakyat', 'umaakyat', 'aakyat', 'N/A'],
            ['goodbye (to say)', 'paalam', 'nagpaalam', 'nagpapaalam', 'magpapaalam', 'N/A'],
            ['graduate (from school)', 'tápos', 'nagtápos', 'nagtatápos', 'magtatápos', '卒業する（そつぎょうする）'],
            ['grant (money/chance)', 'bigay', 'nabigay', 'nagbibigay', 'magbibigay', 'N/A'],
            ['greet (someone)', 'bati', 'bumati', '	bumabati', 'babati', 'N/A'],
            ['grow (become big)', 'laki', 'lumaki', 'lumalaki', 'lálaki', 'N/A'],
            ['guard (look after)', 'bantay', 'nagbantay', 'nagbabantay', 'magbabantay', 'N/A'],
            ['haircut (to have)', 'gupit', 'nagpagupit', 'nagpapagupit', 'magpapagupit', 'N/A'],
            ['hand (to use it)', 'kamay', 'nagkamay', 'nagkakamay', 'magkakamay', 'N/A'],
            ['hand to (something to someone)', 'ábot', 'nag-ábot', 'nag-aábot', 'mag-aábot', 'N/A'],
            ['handshake (to give)', 'kamay', 'nagkamayan', 'nagkakamayan', 'magkakamayan', 'N/A'],
            ['hang(clothes)', 'sampay', 'nagsampay', 'nagsasampay', 'magsasampay', 'N/A'],
            ['happy (become)', 'sayá', 'sumayá', 'sumasayá', 'sasayá', 'N/A'],
            ['happy (to enjoy)', 'sayá', 'nagsayá', 'nagsasayá', 'magsasayá', 'N/A'],
            ['hate', 'suklam', 'nasuklam', 'nasusuklam', 'gagáling', 'N/A'],
            ['heal', 'gáling', 'gumáling', 'gumagáling', 'mahihílo', 'N/A'],
            ['hear (something)', 'dínig', 'nadinig narinig', 'nadidinig naririnig', 'madidinig maririnig', '聞く（きく）'],
            ['hear (someone)', 'kinig', 'nakinig', 'nakikinig', 'makikinig', '聞く（きく）'],
            ['heat up(something)', 'init', 'nag-init', 'nag-iinit', 'mag-iinit', '熱する（ねっする）'],
            ['hello(to say)', 'kumusta', 'nangumusta', 'nangungumusta', 'mangungumusta', 'N/A'],
            ['help', 'tulong', 'tumulong', 'tumutulong', 'tutulong', '手伝う（てつだう）'],
            ['hide (something)', 'tago', 'nagtago', 'nagtatago', 'magtatago', '隠す（かくす）'],
            ['improve', 'buti', 'bumuti', 'bumubuti', 'bubuti', 'N/A'],
            ['insert', 'suot', 'nagsuot', 'nagsusuot', 'magsusuot', '入れる（いれる）'],
            ['install', 'lagay', 'naglagay', 'naglalagay', 'maglalagay', 'N/A'],
            ['introduce (someone)', 'kilala', 'nagpakilala', 'nagpapakilala', 'magpapakilala', '紹介する（しょうかいする'],
            ['introduce (something)', 'kita', 'nagpakita', 'nagpapakita', 'magpapakita', 'N/A'],
            ['invent', 'imbento', 'nag-imbento', 'nag-iimbento', 'mag-imbento', 'でっち上げる（でっちあげる）'],
            ['invite', 'imbita', 'nag-imbita', 'nag-iimbita', 'mag-iimbita', '誘う（さそう）'],
            ['involve', 'sali', 'sumali', 'sumasali', 'sasali', 'N/A'],
            ['join (game)', 'sali', 'sumali', 'sumasali', 'sasali', 'N/A'],
            ['join (someone)', 'sama', 'sumama', 'sumasama', 'sasama', 'N/A'],
            ['joke', 'loko', 'nangloko nanloko', 'nangloloko nanloloko', 'mangloloko manloloko', 'N/A'],
            ['jump', 'talon', 'tumalon', 'tumatalon', 'tatalon', '晴れる（はれる）'],
            ['keep (save)', 'tago', 'nagtago', 'nagtatago', 'magtatago', 'はぶく'],
            ['keep (put aside)', 'tabí', 'nagtabí', 'nagtatabi', 'magtatabí', 'はぶく'],
            ['kill', 'pátay', 'pumátay', 'pumapátay', 'papátay', 'ころす'],
            ['kill (slaughter)', 'katay', 'nagkatay', 'nagkakatay', 'magkakatay', '屠る（ほふる）'],
            ['kiss', 'hálik', 'humálik', 'humahálik', 'hahálik', 'キスする'],
            ['knock (door)', 'kátok', 'kumátok', 'kumakátok', 'kakátok', 'N/A'],
            ['knock down', 'gibá', 'naggibá', 'naggigibá', 'maggigibá', '叩く（たたく）'],
            ['know (someone)', 'kilala', 'nakipag-kilala', 'nakikipag-kilala', 'makikipag-kilala', 'わかる'],
            ['laugh', 'tawa', 'tumawa', 'tumatawa', 'tatawa', '笑う（わらう）'],
            ['laundry', 'labá', 'naglabá', 'naglalabá', 'maglalabá', '洗濯する（せんたくする）'],
            ['lay (put)', 'lágay', 'naglágay', 'naglalágay', 'maglalágay', 'N/A'],
            ['lie (tell a lie)', 'sinungaling', 'nag-sinungaling', 'nag-sisinungaling', 'mag-sisinungaling', '嘘をつく（うそをつく'],
            ['lie down', 'higa', 'humiga', 'humihiga', 'hihiga', 'N/A'],
            ['light up', 'ilaw', 'umilaw', 'umiilaw', 'iilaw', 'N/A'],
            ['listen', 'kinig', 'nakinig', 'nakikinig', 'makikinig', 'N/A'],
            ['loan', 'utang', 'umutang', 'umuutang', 'uutang', 'N/A'],
            ['look', 'tingin', 'tumingin', 'tumitingin', 'titingin', 'N/A'],
            ['lose', 'walá', 'nawalá', 'nawawalá', 'mawawalá', 'N/A'],
            ['love (someone romantically)', 'ibig', 'umibig', 'umiibig', 'iibig', '愛する（あいする）'],
            ['love (someone)', 'mahal', 'nagmahal', 'nagmamahal', 'magmamahal', 'N/A'],
            ['make', 'gáwa', 'gumáwa', 'gumagáwa', 'gagáwa', '作る（つくる）'],
            ['market(go to)', 'palengke', 'na-malengke', 'nama-malengke', 'mama-malengke', 'N/A'],
            ['marry', 'kasal', 'nagpakasal', 'nagpapakasal', 'magpapakasal', 'けこんする'],
            ['measure(weight)', 'timbang', 'nagtimbang', 'nagtitimbang', 'magtitimbang', 'N/A'],
            ['measure (dimension)', 'sukat', 'nagsukat', 'nagsusukat', 'magsusukat', 'N/A'],
            ['meet(someone)', 'kíta', 'nagkíta', 'nagkikíta', 'magkikíta', 'N/A'],
            ['move(transfer)', 'lipat', 'lumipat', 'lumilipat', 'lilipat', 'N/A'],
            ['move (something)', 'lipat', 'naglipat', 'naglilipat', 'maglilipat', 'N/A'],
            ['move over(someone)', 'usog', 'umusog', 'umuusog', 'uusog', 'N/A'],
            ['move over (something)', 'usog', 'nag-usog', 'nag-uusog', 'mag-uusog', 'N/A'],
            ['nap', 'siesta', 'nagsiesta', 'nagsisiesta', 'magsisiesta', 'N/A'],
            ['need', 'kailangan', 'nanga-ilangan', 'nanganga-ilangan', 'manganga-ilangan', 'N/A'],
            ['no (to say no)', 'hindí', 'humindí', 'humihindí', 'hihindí', 'N/A'],
            ['nod', 'tángo', 'tumángo', 'tumatángo', 'tatángo', 'N/A'],
            ['noise', 'ingay', 'nag-ingay', 'nag-iingay', 'mag-iingay', 'N/A'],
            ['obey', 'súnod', 'sumúnod', 'sumúsunod', 'susúnod', 'N/A'],
            ['observe', 'másid', 'nagmásid', 'nagmamásid', 'magmamásid', '見る（みる）'],
            ['occupy', 'okupá', 'nag-okupá', 'nag-ookupá', 'mag-ookupá', 'N/A'],
            ['occur', 'yari', 'nangyari', 'nangyayari', 'mangyayari', 'N/A'],
            ['open (something)', 'búkas', 'nagbúkas', 'nagbubúkas', 'magbubúkas', '開く（ひらく）'],
            ['open (by itself)', 'búkas', 'bumúkas', 'bumubúkas', 'bubúkas', 'N/A'],
            ['order (someone)', 'utos', 'nag-utos', 'nag-uutos', 'mag-uutos', '命じる（めいじる）'],
            ['order (something)', 'order', 'nag-order', 'nag-oorder', 'mag-oorder', 'N/A'],
            ['paint (art)', 'pinta', 'nagpinta', 'nagpipinta', 'magpipinta', 'める'],
            ['paint (on an object)', 'pinta', 'nagpinta', 'nagpipinta', 'magpipinta', 'N/A'],
            ['park(in the garage)', 'garahe', 'naggarahe', 'naggagarahe', 'maggagarahe', 'N/A'],
            ['park (parking lot)', 'parada', 'pumarada', 'pumaparada', 'paparada', 'N/A'],
            ['pass(exam)', 'pasa', 'pumása', 'pumápasa', 'pápasa', 'N/A'],
            ['pass by', 'daan', 'dumaan', 'dumadaan dumaraan', 'dadaan daraan	', 'N/A'],
            ['pass on', 'pasa', 'nagpasa', 'nagpapasa', 'magpapasa', 'N/A'],
            ['pass on(to someone)', 'ábot', 'nag-ábot', 'nag-aábot', 'mag-aábot', 'N/A'],
            ['pawn', 'sanlá', 'nagsanlá', 'nagsasanlá', 'magsasanlá', 'N/A'],
            ['pay', 'bayad', 'nagbayad', 'nagbabayad', 'magbabayad', '支払う（しはらう）'],
            ['peek', 'silip', 'sumilip', 'sumisilip', 'sisilip', 'N/A'],
            ['pick (choose)', 'pili', 'pumili', 'pumipili', 'pipili', 'N/A'],
            ['pick up(something)', 'dampot', 'dumampot', 'dumadampot dumarampot', 'dadampot darampot', 'N/A'],
            ['pick up(someone)', 'sundó', 'nagsundó', 'nagsusundó', 'magsusundó', '迎えうに行く（むかえうにいく）'],
            ['place', 'lagay', 'naglagay', 'naglalagay', 'maglalagay', 'N/A'],
            ['question', 'tanong', 'nagtanong', 'nagtatanong', 'magtatanong', 'きく'],
            ['quick (to make it)', 'bilis', 'bumilis', 'bumibilis', 'bibilis', 'N/A'],
            ['quiet', 'tahimik', 'tumahimik', 'tumatahimik', 'tatahimik', 'N/A'],
            ['quit', 'ayaw', 'umayaw', 'umaayaw', 'aayaw', 'やめる'],
            ['raise (animals)', 'arúga', 'nag - arúga', 'nag-aarúga', 'mag - aarúga', 'N/A'],
            ['raise (baby sit)', 'alaga', 'nag-alaga	', 'nag-aalaga	', 'mag-aalaga	', 'N/A'],
            ['raise (children)', 'laki', 'nagpalaki', 'nagpapalaki', 'magpapalaki', 'N/A'],
            ['raise (hand)', 'taas', 'nagtaas', 'nagtataas', 'magtataas', 'N/A'],
            ['reach (something)', 'abot', 'umabot', 'umaabot', 'aabot', 'N/A'],
            ['reach (destination)', 'dating rating', 'dumating narating', 'dumarating nararating', 'darating mararating', 'N/A'],
            ['read (something)', 'basa', 'nagbása bumasa', 'nagbabása bumabasa', 'magbabása babasa', '読む（よむ）'],
            ['receive', 'tanggap', 'tumanggap', 'tumatanggap', 'tatanggap', 'もらう'],
            ['refuse', 'ayaw', 'umayaw', 'umaayaw', 'aayaw', 'N/A'],
            ['reject', 'tanggi', 'tumanggi', 'tamatanggi', 'tatanggi', 'N/A'],
            ['remember', 'alala', 'naalala', 'naaalala', 'maaalala', 'N/A'],
            ['remove (clothes)', 'hubad', 'naghubad', 'naghuhubad', 'maghuhubad', 'N/A'],
            ['remove (something)', 'alis', 'nag-alis', 'nag-aalis', 'mag-aalis', 'N/A'],
            ['remove (someone)', 'alis', 'nagpaalis', 'nagpapaalis', 'magpapaalis', 'N/A'],
            ['rent (house)', 'upa', 'umupa', 'umuupa', 'uupa', 'N/A'],
            ['rent (car)', 'arkila', 'umarkila', 'umaarkila', 'aarkila', 'N/A'],
            ['sad', 'lungkot', 'nalungkot', 'nalulungkot', 'malulungkot', 'N/A'],
            ['say', 'sabi', 'nagsabi', 'nagsasabi', 'magsasabi', '言う（いう）'],
            ['scare', 'takot', 'natakot', 'natatakot', 'matatakot', 'N/A'],
            ['see', 'kita', 'nakakita', 'nakakakita', 'makakakita', '見る（みる）'],
            ['sell', 'benta', 'nagbenta', 'nagbebenta', 'magbebenta', '売る（うる）'],
            ['sew', 'tahi', 'nagtahi', 'nagtatahi', 'magtatahi', 'めう'],
            ['shout', 'sigaw', 'sumigaw', 'sumisigaw', 'sisigaw', '叫ぶと（さけぶ）'],
            ['shout (at each other)', 'sigaw', 'nagsigawan', 'nagsisigawan', 'magsisigawan', 'N/A'],
            ['sign (signature)', 'pirma', 'pumirma', 'pumipirma', 'pipirma', 'N/A'],
            ['sign (to give a sign)', 'senyas', 'sumenyas', 'sumesenyas', 'sesenyas', 'N/A'],
            ['sing', 'awit', 'umawit', 'umaawit', 'aawit', '歌う（うたう）'],
            ['sink', 'lubog', 'lumubog', 'lumulubog', 'lulubog', 'N/A'],
            ['sit', 'upo', 'umupo', 'umuupo', 'uupo', 'N/A'],
            ['sleep', 'tulog', 'natulog', 'natutulog', 'matutulog', '寝る（ねる）'],
            ['slice', 'hiwa', 'naghiwa', 'naghihiwa', 'maghihiwa', '着る（きる）'],
            ['take', 'kuha', 'kumuha', 'kumukuha', 'kukuha', '取る（とる）'],
            ['take care (of one\'s self)', 'ingat', 'nag - ingat', 'nag - iingat', 'mag - iingat', 'N/A'],
            ['take care (of someone)', 'alaga', 'nag-alaga', 'nag - aalaga', 'nag-aalaga', 'N/A'],
            ['take care(something)', 'ingat', 'nag - ingat', 'nag - iingat', 'mag - iingat', 'N/A'],
            ['talk', 'salita', 'nagsalita', 'nagsasalita', 'magsasalita', '話す（はなす）'],
            ['teach', 'turo', 'nagturo', 'nagtuturo', 'magtuturo', '教える（おしえる）'],
            ['tease', 'biro', 'nagbiro', 'nagbibiro', 'magbibiro', 'N/A'],
            ['tell', 'sabi', 'nagsabi', 'nagsasabi', 'magsasabi', 'N/A'],
            ['test(examine)', 'suri', 'nagsuri', 'nagsusuri', 'magsusuri', 'N/A'],
            ['test(try out)', 'subok', 'sumubok', 'sumusubok', 'susubok', 'N/A'],
            ['tighten', 'higpit', 'naghigpit', 'naghihigpit', 'maghihigpit', 'N/A'],
            ['think', 'isip', 'nag - isip', 'nag - iisip', 'mag - iisip', '思い（おもい）'],
            ['throw', 'tapon', 'nagtapon', 'nagtatapon', 'magtatapon', 'N/A'],
            ['travel (voyage)', 'lakbay', 'naglakbay', 'naglalakbay', 'maglalakbay', 'N/A'],
            ['travel (vacation)', 'bakasyon', 'nagbakasyon', 'nagbabakasyon', 'magbabakasyon', 'N/ A'],
            ['understand (something)', 'intindi', 'umintindi', 'umiintindi', 'iintindi', 'わかる'],
            ['use', 'gamit', 'gumamit', 'gumagamit', 'gagamit', 'つかう'],
            ['vanish', 'wala', 'nawala', 'nawawala', 'mawawala', 'N/A'],
            ['violate (an order)', 'suway', 'sumuway', 'sumusuway', 'susuway', 'N/A'],
            ['violate (a law)', 'labag', 'lumabag', 'lumalabag', 'lalabag', 'N/A'],
            ['visit', 'dalaw', 'dumalaw', 'dumadalaw', 'dadalaw', 'N/A'],
            ['vote', 'boto', 'bumoto', 'bumoboto', 'boboto', 'N/A'],
            ['wait', 'hintay', 'naghintay', 'naghihintay', 'maghihintay', 'まつ'],
            ['walk', 'lakad', 'naglakad', 'naglalakad', 'maglalakad', '歩く（あるく）'],
            ['warn', 'babala', 'nagbabala', 'nagbababala', 'magbababala', 'N/A'],
            ['wash', 'hugas', 'naghugas', 'naghuhugas', 'maghuhugas', 'N/A'],
            ['watch (movie/TV)', 'nood', 'nanood', 'nanonood', 'manonood', '見る（みる）'],
            ['watch over', 'bantay', 'nagbantay', 'nagbabantay', 'magbabantay', 'N/A'],
            ['water(plants)', 'dilig', 'nagdidilig', 'nagdidilig', 'magdidilig', 'N/A'],
            ['wed', 'kasal', 'nagpakasal', 'nagpapakasal', 'nagpapakasal', 'けこんする'],
            ['whisper', 'bulong', 'bumulong', 'bumubulong', 'bubulong', 'ささやく'],
            ['whistle', 'sipol', 'sumipol', 'sumisipol', 'sisipol', 'N/A'],
            ['win', 'wagi', 'nagwagi', 'nagwawagi', 'magwawagi', 'N/A'],
            ['wipe', 'punas', 'nagpunas', 'nagpupunas', 'magpupunas', 'N/A'],
            ['withdraw (money)', 'kuha (withdraw)', 'kumuha (nag-withdraw)', 'kumukuha (nagwi-withdraw)', 'kukuha (magwi-withdraw)', 'N/A'],
            ['withdraw (from activity)', 'alis', 'umalis', 'umaalis', 'aalis', 'N/A'],
            ['wonder (be puzzled)', 'taka', 'nagtaka', 'nagtataka', 'magtataka', 'N/A'],
            ['yawn', 'hikab', 'naghikab', 'naghihikab', 'maghihikab', 'N/A'],
            ['yes (to say yes to)', 'oo', 'umoo', 'umooo', 'ooo', 'N/A']

        ];

        $count = count($verbs);

        foreach ($verbs as $key => $verbData) {
            $verb = new Verb();

            $verb->created_at = Carbon\Carbon::now()->subDays($count)->toDateTimeString();
            $verb->updated_at = Carbon\Carbon::now()->subDays($count)->toDateTimeString();
            $verb->englishTranslation = $verbData[0];
            $verb->filipinoRootTranslation = $verbData[1];
            $verb->filipinoPastTenseTranslation = $verbData[2];
            $verb->filipinoPresentTenseTranslation = $verbData[3];
            $verb->filipinoFutureTenseTranslation = $verbData[4];
            $verb->japaneseRootTranslation = $verbData[5];

            $verb->save();
            $count--;
        }
    }
}
